import { useState } from "react";
import type { TrialApplication } from "../types";
import { validateCode } from "../utils/api";
import FormField from "./FormField";
import TrialRegistration from "./TrialRegistration";

type PlayerJourney = "renewal" | "trial";

type PlayerRegistrationProps = {
  onTrialApplicationSaved: (application: TrialApplication) => void;
  onContinueToOnboarding: () => void;
};

function PlayerRegistration({
  onTrialApplicationSaved,
  onContinueToOnboarding,
}: PlayerRegistrationProps) {
  const [journey, setJourney] = useState<PlayerJourney>("renewal");
  const [membershipNumber, setMembershipNumber] = useState("");
  const [renewalCode, setRenewalCode] = useState("");
  const [message, setMessage] = useState("");
  const [isValidatingRenewal, setIsValidatingRenewal] = useState(false);

  const validateRenewalCode = async () => {
    setIsValidatingRenewal(true);
    setMessage("");

    try {
      await validateCode({
        code: renewalCode.trim(),
        membershipNumber: membershipNumber.trim(),
      });
      setMessage("Renewal code accepted. Continue to Urban Warrior Onboarding.");
      onContinueToOnboarding();
    } catch (error) {
      setMessage(
        error instanceof Error
          ? error.message
          : "Enter a valid membership number and unused renewal code.",
      );
    } finally {
      setIsValidatingRenewal(false);
    }
  };

  return (
    <section className="form-card">
      <div className="intro-panel">
        <p>
          Player registration starts with one of two paths: existing players use
          Renewal, and new players apply through Trial first.
        </p>
      </div>

      <div className="registration-form">
        <div className="journey-selector" role="tablist" aria-label="Player registration path">
          <button
            className={journey === "renewal" ? "active" : ""}
            type="button"
            onClick={() => {
              setJourney("renewal");
              setMessage("");
            }}
          >
            Renewal
          </button>
          <button
            className={journey === "trial" ? "active" : ""}
            type="button"
            onClick={() => {
              setJourney("trial");
              setMessage("");
            }}
          >
            Trial
          </button>
        </div>

        {journey === "renewal" && (
          <div className="path-panel">
            <h2>Renewal</h2>
            <p>
              Existing Urban Warrior players need a renewal code generated by admin
              before onboarding can continue.
            </p>
            {message && <p className="success-message">{message}</p>}
            <FormField label="Membership Number" htmlFor="membershipNumber" required>
              <input
                id="membershipNumber"
                value={membershipNumber}
                onChange={(event) => setMembershipNumber(event.target.value)}
                placeholder="Example: MEM-1001"
              />
            </FormField>
            <FormField label="Renewal Code" htmlFor="renewalCode" required>
              <input
                id="renewalCode"
                value={renewalCode}
                onChange={(event) => setRenewalCode(event.target.value)}
                placeholder="Example: RENEW-123456"
              />
            </FormField>
            <button
              className="submit-button"
              type="button"
              onClick={validateRenewalCode}
              disabled={isValidatingRenewal}
            >
              {isValidatingRenewal ? "Checking..." : "Continue Renewal"}
            </button>
          </div>
        )}

        {journey === "trial" && (
          <div className="path-panel embedded-panel">
            <TrialRegistration onApplicationSaved={onTrialApplicationSaved} />
          </div>
        )}
      </div>
    </section>
  );
}

export default PlayerRegistration;
